name: resumeflutter
description: Portfolio made with Flutter web
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flare_flutter: ^2.0.6
  google_fonts: ^2.0.0
  url_launcher: ^6.0.1
  provider: ^5.0.0-nullsafety.5
  fluttertoast: ^8.0.1-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
